### ISSUE TITLE
Virksomhetens forespørsler/Company requests - Individual components

### ISSUE THREAD

**Issue by Albertlarsen** [Altinn/altinn-authorization-admin#19]
### Description

We need to create several components and styles to be able to create the feature below is shown in pic below. Links can be found below:

- [ ] - Accordion: https://github.com/Altinn/altinn-design-system/issues/28
- [ ] - List: https://github.com/Altinn/altinn-design-system/issues/27
- [ ] - Dashed list style: https://github.com/Altinn/altinn-design-system/issues/78
- [ ] - Toggle button group: https://github.com/Altinn/altinn-design-system/issues/24
- [ ] - Popover: https://github.com/Altinn/altinn-design-system/issues/58
- [ ] - IconButton: https://github.com/Altinn/altinn-design-system/issues/79
- [ ] - Accordion blue arrow style: https://github.com/Altinn/altinn-design-system/issues/91
- [ ] - Button variant action: https://github.com/Altinn/altinn-design-system/issues/26

![image](https://user-images.githubusercontent.com/31471142/184155568-bd22b278-6d2b-4582-8e98-0ee7a767853d.png)
